name: Your New Jekyll Site
markdown: redcarpet
pygments: true

exclude:
  - Gemfile
  - Gemfile.lock
  - Procfile
  - README.md
  - tasks

# defaults
# sass:
#   syntax: scss        # scss|sass
#   style:  compressed  # nested|expanded|compact|compressed
assets:
  js_compressor:  uglifier
  css_compressor: sass
